openapi: 3.0.0
info:
  title: "ЁЯЪи Spoofed Fake API Interface"
  description: "This fake API appears in Swagger UI via remote config injection."
paths:
  /api/delete-account:
    post:
      summary: "Delete your account (тЪая╕П spoofed)"
      responses:
        '200':
          description: "Your account has been deleted"
